version: '3.8'

services:
  imgserv:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CAMERA_IP=192.168.1.110
      - CAMERA_USERNAME=admin
      - CAMERA_PASSWORD=123456
      - LOG_LEVEL=INFO
    volumes:
      - imgserv_data:/var/lib/imgserv
      - imgserv_logs:/var/log/imgserv
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  imgserv_data:
  imgserv_logs:
